// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi4SUAI8qwMnuuuyQ_ha53Y6qIdRnUWB8',
    appId: '1:768850852696:web:d45571ce928d38e170432d',
    messagingSenderId: '768850852696',
    projectId: 'brand-a21e2',
    authDomain: 'brand-a21e2.firebaseapp.com',
    storageBucket: 'brand-a21e2.appspot.com',
    measurementId: 'G-TYYC2SZHQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl1NYOR4IKxjgyw9ZAHk_mBgJikEdWlaE',
    appId: '1:768850852696:android:f67748341ff014d370432d',
    messagingSenderId: '768850852696',
    projectId: 'brand-a21e2',
    storageBucket: 'brand-a21e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB8xMvMtveBizIZiEPS7qPR_g7voD75Cw',
    appId: '1:768850852696:ios:e515f5875b3ec8e670432d',
    messagingSenderId: '768850852696',
    projectId: 'brand-a21e2',
    storageBucket: 'brand-a21e2.appspot.com',
    iosBundleId: 'com.example.resturent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB8xMvMtveBizIZiEPS7qPR_g7voD75Cw',
    appId: '1:768850852696:ios:e515f5875b3ec8e670432d',
    messagingSenderId: '768850852696',
    projectId: 'brand-a21e2',
    storageBucket: 'brand-a21e2.appspot.com',
    iosBundleId: 'com.example.resturent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlJdXEfr_aJDEl80o2mwOudpzmcJNmIBU',
    appId: '1:768850852696:web:bdc5faa45f42484370432d',
    messagingSenderId: '768850852696',
    projectId: 'brand-a21e2',
    authDomain: 'brand-a21e2.firebaseapp.com',
    storageBucket: 'brand-a21e2.appspot.com',
    measurementId: 'G-1KNS4YMV62',
  );
}
