name: resturent
description: A modern restaurant application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  intl: ^0.20.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  awesome_notifications: ^0.10.1
  table_calendar: ^3.0.9
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
